keys:
  - &ludovico age1jedat345uwjtvjl2uyd05n04yq5zdqr37lz2p95vl3hjv0eahadst74x23
  - &sforza age16gslehwlwjq202wrkc0gmrsts63y8mhyuxdwukhvpwkvlg0pyclsc2xu6j
  - &nostra age1xqsmqu9flpp8tzf2y0f03vnzwrzmhnr9fau9l2m5phsxa9tcqagsh084p5
creation_rules:
  - path_regex: hosts/sforza/secrets.yaml
    key_groups:
      - age:
        - *ludovico
        - *sforza
  - path_regex: hosts/nostra/secrets.yaml
    key_groups:
      - age:
        - *nostra
        - *ludovico
