name: "Build flake"
on:
  pull_request:
  push:
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Flake show
      run: nix flake show

  generate_matrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix

  build_flake:
    runs-on: ubuntu-latest
    needs: [generate_matrix]
    strategy:
      fail-fast: false
      max-parallel: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Set up cachix
      uses: cachix/cachix-action@master
      with:
        name: sforza
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pathsToPush: result
    - name: Build output

  eval:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        output: [
          nixosConfigurations.sforza.config.system.build.toplevel,
          nixosConfigurations.nostra.config.system.build.toplevel,
          homeConfigurations.ludovico.activationPackage
        ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Set up cachix
      uses: cachix/cachix-action@master
      with:
        name: sforza
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Eval output
      run: nix build .#${{ matrix.output }} -L --dry-run --print-out-paths -j0
