# https://github.com/thiagokokada/nix-configs
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v7
        with:
          overprovision-lvm: true
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true
          root-reserve-mb: 512
          swap-size-mb: 1024
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: access-tokens = github.com=${{ secrets.GH_TOKEN }}
          nix_path: nixpkgs=channel:master
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
          name: sforza
      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch master
      - name: Validate Flakes
        run: nix flake check
      - name: 'Build Home-Manager configs for: ludovico'
        run: |-
          nix build --print-build-logs '.#homeConfigurations.ludovico.activationPackage'
name: build-home-manager-and-cache
"on":
  - push
  - workflow_dispatch
