name: Deadnix Analysis

on:
  pull_request:
  push:

jobs:
  deadnix:
    name: Dead Nix Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: astro/deadnix-action@v1
