name: Flake Inputs Checker

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"

jobs:
  flake-inputs-checker:
    name: Flake Inputs Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
