name: Update Flakes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * SAT,TUE" # At 12:00 on Saturday & Tuesday (UTC)

jobs:
  get-flakes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-flakes.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.MAXI_TOKEN }}
            experimental-features = nix-command flakes recursive-nix
      - id: get-flakes
        run: |
          get_flake_inputs() {
            nix flake metadata --json \
              | jq -c '
                  .locks.nodes.root.inputs
                  | {flake: keys}'
          }

          echo "::set-output name=matrix::$(get_flake_inputs)"

  update-flake:
    name: update-${{ matrix.flake }}
    runs-on: ubuntu-latest
    needs: get-flakes
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-flakes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: cachix/install-nix-action@v23
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.18.1/install"
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.MAXI_TOKEN }}
            experimental-features = nix-command flakes recursive-nix
      - run: git config --global user.email "59017537+MaximilianSforza@users.noreply.github.com"
      - run: git config --global user.name "Maximilian"
      - uses: cpcloud/flake-update-action@v1.0.2
        with:
          dependency: ${{ matrix.flake }}
          pull-request-token: ${{ secrets.PR_TOKEN }}
          pull-request-author: Maximilian <59017537+MaximilianSforza@users.noreply.github.com>
          delete-branch: true
          github-token: ${{ secrets.MAXI_TOKEN }}
          pull-request-branch-prefix: update-
          automerge: true
