# https://github.com/fortuneteller2k/nix-config/blob/master/.github/workflows/format.yml
name: "nix-config format check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.17.1/install"

      - run: nix run nixpkgs#alejandra -- --check ./
