name: Nix Format Checker

on:
  pull_request:
  push:

jobs:
  format:
    name: Run Alejandra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix run nixpkgs#alejandra -- --check ./
