name: "Nvfetcher Update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  nvfetcher-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_TOKEN }}"

      - name: Install nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Git config
        run: |
          git config --global user.email "lewdovico@gnuweeb.org"
          git config --global user.name "Ludovico Piero"

      - name: Run nvfetcher
        run: |
          pushd pkgs
          nix run nixpkgs#nvfetcher -- --commit-changes
          popd

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: "${{ secrets.GH_TOKEN }}"
          delete-branch: true

  automerge:
    needs: nvfetcher-update

    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          # A personal access token that you have generated and saved in the
          # repo or org’s encrypted secrets
          github-token: ${{ secrets.GH_TOKEN }}

          # The name of the PR author to enable automerge for
          # Defaults to dependabot[bot]
          allowed-author: "Ludovico Piero"

          # Allowed values: MERGE | SQUASH | REBASE
          # Defaults to MERGE
          merge-method: MERGE
