name: Nix Lint and Suggestions Checker

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"

jobs:
  statix:
    name: Run statix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - run: nix run nixpkgs#statix -- check ./
