name: Nix Lint and Suggestions Checker

on:
  pull_request:
  push:

jobs:
  statix:
    name: Run statix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix run nixpkgs#statix -- check ./
