# https://github.com/fortuneteller2k/nix-config/blob/master/.github/workflows/statix.yml
name: "nix-config statix check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - uses: cachix/install-nix-action@v20
      with:
        install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.15.0pre20230403_acc3314/install
        extra_nix_config: |
          experimental-features = ca-references ca-derivations nix-command flakes
    - run: nix run nixpkgs#statix -- check ./
