# https://github.com/fortuneteller2k/nix-config/blob/master/.github/workflows/statix.yml
name: "nix-config statix check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v23

      - run: nix run nixpkgs#statix -- check ./
