name: Nix Lint and Suggestions Checker

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.lua"
      - "**/*.el"

jobs:
  statix:
    name: Run statix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
      - run: nix run nixpkgs#statix -- check ./
